export const GROUPS = [
  'lithium family, alkali metals',
  'beryllium family, alkaline earth metals',
  'scandium family',
  'titanium family',
  'vanadium family',
  'chromium family',
  'manganese family',
  'iron family',
  'cobalt family',
  'nickel family',
  'copper family',
  'zinc family',
  'boron family',
  'carbon family',
  'nitrogen family, pnictogens',
  'oxygen family, chalcogens',
  'fluorine family, halogens',
  'helium/neon family, noble gases',
  'n/a',
];
