export const GROUPS = [
  'alkali metals, or lithium family',
  'alkaline earth metals, or beryllium family',
  'scandium family',
  'titanium family',
  'vanadium family',
  'chromium family',
  'manganese family',
  'iron family',
  'cobalt family',
  'nickel family',
  'copper family',
  'zinc family',
  'boron family',
  'carbon family',
  'Pnictogens, or nitrogen family',
  'Chalcogens, or oxygen family',
  'Halogens, or fluorine family',
  'Noble Gases, or helium/neon family',
];
