version: '3'
services:

  server:
    build: .
    container_name: server
    expose:
      - ${PORT}
    environment: 
      PORT: ${PORT}
    ports: 
      - ${PORT}:${PORT}
      

  client:
    build: ./client
    container_name: client
    volumes:
      - ./client:/client
      - /client/node_modules
    expose:
      - 4200
    ports: 
      - 4200:80
    links:
      - server