version: '3'
services:

  server:
    build: .
    container_name: server
    expose:
      - ${PORT}
    environment: 
      PORT: ${PORT}
    ports: 
      - ${PORT}:${PORT}
    volumes:
      - ./server:/server
      - /server/node_modules
      

  client:
    build: ./client
    container_name: client
    volumes:
      - ./client:/client
      - /client/node_modules
    links:
      - server