-- CreateTable
CREATE TABLE "Element" (
    "id" SERIAL NOT NULL,
    "atomicNumber" INTEGER NOT NULL,
    "element" TEXT NOT NULL,
    "symbol" TEXT NOT NULL,
    "atomicMass" INTEGER NOT NULL,
    "neutrons" INTEGER NOT NULL,
    "protons" INTEGER NOT NULL,
    "electrons" INTEGER NOT NULL,
    "period" INTEGER NOT NULL,
    "group" INTEGER NOT NULL,
    "phase" TEXT NOT NULL,
    "radioactive" BOOLEAN NOT NULL,
    "natural" BOOLEAN NOT NULL,
    "metal" BOOLEAN NOT NULL,
    "nonmetal" BOOLEAN NOT NULL,
    "metalloid" BOOLEAN NOT NULL,
    "type" TEXT NOT NULL,
    "atomicRadius" INTEGER NOT NULL,
    "electronegativity" INTEGER NOT NULL,
    "firstIonization" INTEGER NOT NULL,
    "density" TEXT NOT NULL,
    "meltingPoint" INTEGER NOT NULL,
    "boilingPoint" INTEGER NOT NULL,
    "isotopes" INTEGER NOT NULL,
    "discoverer" TEXT NOT NULL,
    "discovered" INTEGER NOT NULL,
    "specificHeat" INTEGER NOT NULL,
    "shells" INTEGER NOT NULL,
    "valence" INTEGER NOT NULL,

    CONSTRAINT "Element_pkey" PRIMARY KEY ("id")
);
